### PR TITLE
login_signup_page_usingFirebaseDatabase

### PR DESCRIPTION
**Pull request by daksh80**
This is a login page and signup page in this page student register yourself by signup page and those data are store in our Firebase Database for analytics 
In this login and signup page their are some bugs which i am going to teel you
.you can't login without signup if you are doing that then program should be crushed
2.you can't signup just like (daksh , victor) you need to specify mail id properly just like (pal.dakshendra90@gmail.com)
3.you can't use same account for signup
Sorry,but I can't fix these bugs right now because we have very less time

### CODE REVIEW

**Comment by rishiagrawal2609** [comment]
# Well Done  but keeps on crashing
 add pubspecs.yml to .gitignore file and resend the pull request.

**Comment by daksh80** [comment]
pubspecs.yml file are already uploaded

**Comment by daksh80** [comment]
i can't delete my pubspecs.yml file .if i delete pubspecs.yml file firebase will stop working

**Comment by daksh80** [comment]
thank you

**Pull request merged**
